spring:
  application:
    name: eurekaserver
  security:
    basic:
      enable: true
    user:
      name: cursoms-eureka-server
      password: ecok-usr-eeuramssur
      
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
